#!/usr/bin/env bash

# Extract the wifi username (SSID)
# Refer: "iw dev wlan0 link" command output for this
ssid=$(iw dev wlan0 link | grep 'SSID' | awk '{print $2}')

echo "Connected WiFi SSID: $ssid"